[MXP-6964] Use protobuf default value when ingesting vehicles
wearefair/protobuf-to-dict pull request #12
Opened 2022-03-16 10:57 UTC by Evgenii-Basmov

[MXP-6964](https://faircorp.atlassian.net/browse/MXP-6964)

2022-03-16 20:32 UTC, haigsant approved these changes

2022-03-16 20:47 UTC, seperman-fair requested changes
Unit tests missing for these changes

2022-03-17 11:23 UTC, Evgenii-Basmov commented
@seperman-fair updated unit test to reflect changes

2022-03-18 16:46 UTC, seperman-fair approved these changes
lgtm

2022-03-20 07:55 UTC, merged