Fd 1734 handling uppercase enums
wearefair/protobuf-to-dict pull request #2
Opened 2018-01-03 21:23 UTC by seperman

2018-01-04 22:27 UTC, mxl519 commented
How/where in our code are we using this library? I'm a bit wary of relying on a library that has such limited contribution/support for it.

2018-01-08 19:33 UTC, seperman commented
@mxl519 We are using it to convert protobuf objects back and forth to Python dictionaries. We are supporting the library ourselves at this point. It is a small library, nothing to worry about.

2018-01-08 21:03 UTC, mxl519 approved these changes

2018-01-08 21:05 UTC, mxl519 requested changes
Actually, bump setup.py first, then lgtm

2018-01-08 21:06 UTC, seperman commented
@mxl519 Not sure what you mean by setup.py is already bumped to `0.2.3`

2018-01-08 21:08 UTC, mxl519 approved these changes
nvm i'm dumb

2018-01-08 21:10 UTC, merged